# Generated by Django 5.1.5 on 2025-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('caterer', 'Caterer'), ('admin', 'Admin')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
