# Generated by Django 5.1.5 on 2025-01-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen_name', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.block')),
                ('caterer', models.ForeignKey(limit_choices_to={'role': 'caterer'}, on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
