# Generated by Django 5.1.5 on 2025-01-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canteens', to='main.block'),
        ),
    ]
