# Generated by Django 5.1.4 on 2025-03-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_canteen_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
