from django.urls import path
from . import views
urlpatterns = [
    path('get_usernotifications/',views.get_usernotifications, name='get_usernotifications'),
    path('get-notifications/', views.get_notifications, name='get_notifications'),
    path('blocks/<int:block_id>/canteens/', views.block_canteens, name='block_canteens'),
    # path('canteen/<int:canteen_id>/item/add/', views.add_item, name='add_item'),
    path('caterer/main/', views.caterer_main, name='caterer_main'),
    path('canteen/<int:canteen_id>/menu/', views.canteen_menu, name='canteen_menu'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/<int:id>/edit/', views.update_user, name='update_user'),
    path('users/<int:id>/delete/', views.delete_user, name='delete_user'),
    path('manage-blocks/', views.manage_blocks, name='manage_blocks'),
    path('add/', views.add_block, name='add_block'),
    path('update/<int:pk>/', views.update_block, name='update_block'),
    path('delete/<int:pk>/', views.delete_block, name='delete_block'),
    path('manage-canteen/', views.manage_canteen, name='manage_canteen'),
    path('canteens/<int:id>/delete/', views.delete_canteen, name='delete_canteen'),
    path('canteen/add/', views.add_canteen, name='add_canteen'),
    path('canteen/update/<int:id>/', views.update_canteen, name='update_canteen'),
    path('manage-items/', views.manage_items, name='manage_items'),
    path('add-item/', views.add_item, name='add_item'),
    path('update-item/<int:item_id>/', views.update_item, name='update_item'),
    path('delete-item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:item_id>/',views.add_to_cart, name='add-to-cart'),
    path('cart/remove/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
    path('cart/update/<int:pk>/<str:action>/', views.update_cart_quantity, name='update-cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-summary/', views.order_summary, name='order-summary'),
    path('process-payment/', views.process_payment, name='process-payment'),
    path('caterer/orders/', views.caterer_orders, name='caterer_orders'),
    path('caterer/orders/active/', views.active_orders, name='active_orders'),  
    path('caterer/completed-orders/', views.completed_orders, name='completed_orders'),
    path('add_review/<int:item_id>/', views.add_review, name='add_review'),
    path('reviews/', views.caterer_reviews, name='caterer_reviews'),
]


