# Generated by Django 5.1.5 on 2025-02-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_canteen_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('price', models.FloatField()),
                ('pieces', models.IntegerField(default=6)),
                ('category', models.CharField(blank=True, choices=[('Special', 'Special'), ('Juice', 'Juice'), ('Shake', 'Shake'), ('Snack', 'Snack')], max_length=25)),
                ('instructions', models.CharField(default='Not available', max_length=250)),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('labels', models.CharField(blank=True, choices=[('BestSeller', 'BestSeller'), ('New', 'New'), ('Spicy🔥', 'Spicy🔥')], max_length=25)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.canteen')),
            ],
        ),
    ]
