# Generated by Django 5.1.5 on 2025-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=250),
        ),
    ]
