# Generated by Django 5.1.5 on 2025-02-16 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0005_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
