# Generated by Django 5.1.5 on 2025-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0006_alter_cartitem_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Preparing', max_length=20),
        ),
    ]
