# Generated by Django 5.1.5 on 2025-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0007_alter_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
