# Generated by Django 5.1.5 on 2025-03-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0009_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
