# Generated by Django 5.1.4 on 2025-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0011_cartitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cart_items',
            field=models.ManyToManyField(related_name='paid_payments', to='canteenapp.cartitem'),
        ),
    ]
